### ISSUE TITLE
return to previous work

### ISSUE THREAD

**Issue by rlzijdeman** [netwerk-digitaal-erfgoed/LDWizard#30]
Hi

Would it be possible to export one's click-and-point action to a ldwizard format, that would allow you to retrieve earlier point-and-click actions? E.g. suppose I make some decision on the properties and later decide I want one or two changed. Would I need to do all the other columns again?

**Comment by wouterbeek** [comment]
In the future it should indeed be possible to run the LD Wizard, export/publish the script, and then load the script later to automatically initialize the GUI accordingly.  This feature is already described in the design document, but we did not implement it yet because this turned out to be too complex for the initial LD Wizard project.

**Comment by ivozandhuis** [comment]
See: https://github.com/netwerk-digitaal-erfgoed/LDWizard/issues/17

**Comment by wouterbeek** [comment]
Continuing this in #17.
